apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pnba0agpb-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pnba0agpb-nodejs 
  name: pnba0agpb-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pnba0agpb-nodejs 
